//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace detren_sokolova_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_has_shift
    {
        public int id { get; set; }
        public Nullable<int> id_employee { get; set; }
        public Nullable<int> id_shift { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual shift shift { get; set; }
    }
}
