//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace detren_sokolova_v1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class de41_sokolova_v1_eduEntities1 : DbContext
    {

        private static de41_sokolova_v1_eduEntities1 _context;
        public de41_sokolova_v1_eduEntities1()
            : base("name=de41_sokolova_v1_eduEntities1")
        {
        }

        public static de41_sokolova_v1_eduEntities1 GetContext()
        {
            if (_context == null)
                _context = new de41_sokolova_v1_eduEntities1();
            return _context;
        }
    
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<employee_has_shift> employee_has_shift { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<order_has_product> order_has_product { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<shift> shift { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
