//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace detren_sokolova_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_has_product
    {
        public int id { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<int> id_product { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
